<?php
// database/seeders/RegencySeeder.php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class RegencySeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            // ACEH (11)
            ['id'=>'11.01','province_id'=>'11','name'=>'KAB. SIMEULUE'],
            ['id'=>'11.02','province_id'=>'11','name'=>'KAB. ACEH SINGKIL'],
            ['id'=>'11.03','province_id'=>'11','name'=>'KAB. ACEH SELATAN'],
            ['id'=>'11.04','province_id'=>'11','name'=>'KAB. ACEH TENGGARA'],
            ['id'=>'11.05','province_id'=>'11','name'=>'KAB. ACEH TIMUR'],
            ['id'=>'11.06','province_id'=>'11','name'=>'KAB. ACEH TENGAH'],
            ['id'=>'11.07','province_id'=>'11','name'=>'KAB. ACEH BARAT'],
            ['id'=>'11.08','province_id'=>'11','name'=>'KAB. ACEH BESAR'],
            ['id'=>'11.09','province_id'=>'11','name'=>'KAB. PIDIE'],
            ['id'=>'11.10','province_id'=>'11','name'=>'KAB. BIREUEN'],
            ['id'=>'11.11','province_id'=>'11','name'=>'KAB. ACEH UTARA'],
            ['id'=>'11.12','province_id'=>'11','name'=>'KAB. ACEH BARAT DAYA'],
            ['id'=>'11.13','province_id'=>'11','name'=>'KAB. GAYO LUES'],
            ['id'=>'11.14','province_id'=>'11','name'=>'KAB. ACEH TAMIANG'],
            ['id'=>'11.15','province_id'=>'11','name'=>'KAB. NAGAN RAYA'],
            ['id'=>'11.16','province_id'=>'11','name'=>'KAB. ACEH JAYA'],
            ['id'=>'11.17','province_id'=>'11','name'=>'KAB. BENER MERIAH'],
            ['id'=>'11.18','province_id'=>'11','name'=>'KAB. PIDIE JAYA'],
            ['id'=>'11.71','province_id'=>'11','name'=>'KOTA BANDA ACEH'],
            ['id'=>'11.72','province_id'=>'11','name'=>'KOTA SABANG'],
            ['id'=>'11.73','province_id'=>'11','name'=>'KOTA LANGSA'],
            ['id'=>'11.74','province_id'=>'11','name'=>'KOTA LHOKSEUMAWE'],
            ['id'=>'11.75','province_id'=>'11','name'=>'KOTA SUBULUSSALAM'],
            // SUMATERA UTARA (12)
            ['id'=>'12.01','province_id'=>'12','name'=>'KAB. NIAS'],
            ['id'=>'12.02','province_id'=>'12','name'=>'KAB. MANDAILING NATAL'],
            ['id'=>'12.03','province_id'=>'12','name'=>'KAB. TAPANULI SELATAN'],
            ['id'=>'12.04','province_id'=>'12','name'=>'KAB. TAPANULI TENGAH'],
            ['id'=>'12.05','province_id'=>'12','name'=>'KAB. TAPANULI UTARA'],
            ['id'=>'12.06','province_id'=>'12','name'=>'KAB. TOBA'],
            ['id'=>'12.07','province_id'=>'12','name'=>'KAB. LABUHANBATU'],
            ['id'=>'12.08','province_id'=>'12','name'=>'KAB. ASAHAN'],
            ['id'=>'12.09','province_id'=>'12','name'=>'KAB. SIMALUNGUN'],
            ['id'=>'12.10','province_id'=>'12','name'=>'KAB. DAIRI'],
            ['id'=>'12.11','province_id'=>'12','name'=>'KAB. KARO'],
            ['id'=>'12.12','province_id'=>'12','name'=>'KAB. DELI SERDANG'],
            ['id'=>'12.13','province_id'=>'12','name'=>'KAB. LANGKAT'],
            ['id'=>'12.14','province_id'=>'12','name'=>'KAB. NIAS SELATAN'],
            ['id'=>'12.15','province_id'=>'12','name'=>'KAB. HUMBANG HASUNDUTAN'],
            ['id'=>'12.16','province_id'=>'12','name'=>'KAB. PAKPAK BHARAT'],
            ['id'=>'12.17','province_id'=>'12','name'=>'KAB. SAMOSIR'],
            ['id'=>'12.18','province_id'=>'12','name'=>'KAB. SERDANG BEDAGAI'],
            ['id'=>'12.19','province_id'=>'12','name'=>'KAB. BATU BARA'],
            ['id'=>'12.20','province_id'=>'12','name'=>'KAB. PADANG LAWAS UTARA'],
            ['id'=>'12.21','province_id'=>'12','name'=>'KAB. PADANG LAWAS'],
            ['id'=>'12.22','province_id'=>'12','name'=>'KAB. LABUHANBATU SELATAN'],
            ['id'=>'12.23','province_id'=>'12','name'=>'KAB. LABUHANBATU UTARA'],
            ['id'=>'12.24','province_id'=>'12','name'=>'KAB. NIAS UTARA'],
            ['id'=>'12.25','province_id'=>'12','name'=>'KAB. NIAS BARAT'],
            ['id'=>'12.71','province_id'=>'12','name'=>'KOTA SIBOLGA'],
            ['id'=>'12.72','province_id'=>'12','name'=>'KOTA TANJUNGBALAI'],
            ['id'=>'12.73','province_id'=>'12','name'=>'KOTA PEMATANGSIANTAR'],
            ['id'=>'12.74','province_id'=>'12','name'=>'KOTA TEBING TINGGI'],
            ['id'=>'12.75','province_id'=>'12','name'=>'KOTA MEDAN'],
            ['id'=>'12.76','province_id'=>'12','name'=>'KOTA BINJAI'],
            ['id'=>'12.77','province_id'=>'12','name'=>'KOTA PADANGSIDIMPUAN'],
            ['id'=>'12.78','province_id'=>'12','name'=>'KOTA GUNUNGSITOLI'],
            // RIAU (14)
            ['id'=>'14.01','province_id'=>'14','name'=>'KAB. KUANTAN SINGINGI'],
            ['id'=>'14.02','province_id'=>'14','name'=>'KAB. INDRAGIRI HULU'],
            ['id'=>'14.03','province_id'=>'14','name'=>'KAB. INDRAGIRI HILIR'],
            ['id'=>'14.04','province_id'=>'14','name'=>'KAB. PELALAWAN'],
            ['id'=>'14.05','province_id'=>'14','name'=>'KAB. SIAK'],
            ['id'=>'14.06','province_id'=>'14','name'=>'KAB. KAMPAR'],
            ['id'=>'14.07','province_id'=>'14','name'=>'KAB. ROKAN HULU'],
            ['id'=>'14.08','province_id'=>'14','name'=>'KAB. BENGKALIS'],
            ['id'=>'14.09','province_id'=>'14','name'=>'KAB. ROKAN HILIR'],
            ['id'=>'14.10','province_id'=>'14','name'=>'KAB. KEPULAUAN MERANTI'],
            ['id'=>'14.71','province_id'=>'14','name'=>'KOTA PEKANBARU'],
            ['id'=>'14.73','province_id'=>'14','name'=>'KOTA DUMAI'],
            // DKI JAKARTA (31)
            ['id'=>'31.01','province_id'=>'31','name'=>'KAB. KEPULAUAN SERIBU'],
            ['id'=>'31.71','province_id'=>'31','name'=>'KOTA JAKARTA SELATAN'],
            ['id'=>'31.72','province_id'=>'31','name'=>'KOTA JAKARTA TIMUR'],
            ['id'=>'31.73','province_id'=>'31','name'=>'KOTA JAKARTA PUSAT'],
            ['id'=>'31.74','province_id'=>'31','name'=>'KOTA JAKARTA BARAT'],
            ['id'=>'31.75','province_id'=>'31','name'=>'KOTA JAKARTA UTARA'],
            // JAWA BARAT (32)
            ['id'=>'32.01','province_id'=>'32','name'=>'KAB. BOGOR'],
            ['id'=>'32.02','province_id'=>'32','name'=>'KAB. SUKABUMI'],
            ['id'=>'32.03','province_id'=>'32','name'=>'KAB. CIANJUR'],
            ['id'=>'32.04','province_id'=>'32','name'=>'KAB. BANDUNG'],
            ['id'=>'32.05','province_id'=>'32','name'=>'KAB. GARUT'],
            ['id'=>'32.06','province_id'=>'32','name'=>'KAB. TASIKMALAYA'],
            ['id'=>'32.07','province_id'=>'32','name'=>'KAB. CIAMIS'],
            ['id'=>'32.08','province_id'=>'32','name'=>'KAB. KUNINGAN'],
            ['id'=>'32.09','province_id'=>'32','name'=>'KAB. CIREBON'],
            ['id'=>'32.10','province_id'=>'32','name'=>'KAB. MAJALENGKA'],
            ['id'=>'32.11','province_id'=>'32','name'=>'KAB. SUMEDANG'],
            ['id'=>'32.12','province_id'=>'32','name'=>'KAB. INDRAMAYU'],
            ['id'=>'32.13','province_id'=>'32','name'=>'KAB. SUBANG'],
            ['id'=>'32.14','province_id'=>'32','name'=>'KAB. PURWAKARTA'],
            ['id'=>'32.15','province_id'=>'32','name'=>'KAB. KARAWANG'],
            ['id'=>'32.16','province_id'=>'32','name'=>'KAB. BEKASI'],
            ['id'=>'32.17','province_id'=>'32','name'=>'KAB. BANDUNG BARAT'],
            ['id'=>'32.18','province_id'=>'32','name'=>'KAB. PANGANDARAN'],
            ['id'=>'32.71','province_id'=>'32','name'=>'KOTA BOGOR'],
            ['id'=>'32.72','province_id'=>'32','name'=>'KOTA SUKABUMI'],
            ['id'=>'32.73','province_id'=>'32','name'=>'KOTA BANDUNG'],
            ['id'=>'32.74','province_id'=>'32','name'=>'KOTA CIREBON'],
            ['id'=>'32.75','province_id'=>'32','name'=>'KOTA BEKASI'],
            ['id'=>'32.76','province_id'=>'32','name'=>'KOTA DEPOK'],
            ['id'=>'32.77','province_id'=>'32','name'=>'KOTA CIMAHI'],
            ['id'=>'32.78','province_id'=>'32','name'=>'KOTA TASIKMALAYA'],
            ['id'=>'32.79','province_id'=>'32','name'=>'KOTA BANJAR'],
            // JAWA TENGAH (33)
            ['id'=>'33.01','province_id'=>'33','name'=>'KAB. CILACAP'],
            ['id'=>'33.02','province_id'=>'33','name'=>'KAB. BANYUMAS'],
            ['id'=>'33.03','province_id'=>'33','name'=>'KAB. PURBALINGGA'],
            ['id'=>'33.04','province_id'=>'33','name'=>'KAB. BANJARNEGARA'],
            ['id'=>'33.05','province_id'=>'33','name'=>'KAB. KEBUMEN'],
            ['id'=>'33.06','province_id'=>'33','name'=>'KAB. PURWOREJO'],
            ['id'=>'33.07','province_id'=>'33','name'=>'KAB. WONOSOBO'],
            ['id'=>'33.08','province_id'=>'33','name'=>'KAB. MAGELANG'],
            ['id'=>'33.09','province_id'=>'33','name'=>'KAB. BOYOLALI'],
            ['id'=>'33.10','province_id'=>'33','name'=>'KAB. KLATEN'],
            ['id'=>'33.11','province_id'=>'33','name'=>'KAB. SUKOHARJO'],
            ['id'=>'33.12','province_id'=>'33','name'=>'KAB. WONOGIRI'],
            ['id'=>'33.13','province_id'=>'33','name'=>'KAB. KARANGANYAR'],
            ['id'=>'33.14','province_id'=>'33','name'=>'KAB. SRAGEN'],
            ['id'=>'33.15','province_id'=>'33','name'=>'KAB. GROBOGAN'],
            ['id'=>'33.16','province_id'=>'33','name'=>'KAB. BLORA'],
            ['id'=>'33.17','province_id'=>'33','name'=>'KAB. REMBANG'],
            ['id'=>'33.18','province_id'=>'33','name'=>'KAB. PATI'],
            ['id'=>'33.19','province_id'=>'33','name'=>'KAB. KUDUS'],
            ['id'=>'33.20','province_id'=>'33','name'=>'KAB. JEPARA'],
            ['id'=>'33.21','province_id'=>'33','name'=>'KAB. DEMAK'],
            ['id'=>'33.22','province_id'=>'33','name'=>'KAB. SEMARANG'],
            ['id'=>'33.23','province_id'=>'33','name'=>'KAB. TEMANGGUNG'],
            ['id'=>'33.24','province_id'=>'33','name'=>'KAB. KENDAL'],
            ['id'=>'33.25','province_id'=>'33','name'=>'KAB. BATANG'],
            ['id'=>'33.26','province_id'=>'33','name'=>'KAB. PEKALONGAN'],
            ['id'=>'33.27','province_id'=>'33','name'=>'KAB. PEMALANG'],
            ['id'=>'33.28','province_id'=>'33','name'=>'KAB. TEGAL'],
            ['id'=>'33.29','province_id'=>'33','name'=>'KAB. BREBES'],
            ['id'=>'33.71','province_id'=>'33','name'=>'KOTA MAGELANG'],
            ['id'=>'33.72','province_id'=>'33','name'=>'KOTA SURAKARTA'],
            ['id'=>'33.73','province_id'=>'33','name'=>'KOTA SALATIGA'],
            ['id'=>'33.74','province_id'=>'33','name'=>'KOTA SEMARANG'],
            ['id'=>'33.75','province_id'=>'33','name'=>'KOTA PEKALONGAN'],
            ['id'=>'33.76','province_id'=>'33','name'=>'KOTA TEGAL'],
            // DI YOGYAKARTA (34)
            ['id'=>'34.01','province_id'=>'34','name'=>'KAB. KULON PROGO'],
            ['id'=>'34.02','province_id'=>'34','name'=>'KAB. BANTUL'],
            ['id'=>'34.03','province_id'=>'34','name'=>'KAB. GUNUNGKIDUL'],
            ['id'=>'34.04','province_id'=>'34','name'=>'KAB. SLEMAN'],
            ['id'=>'34.71','province_id'=>'34','name'=>'KOTA YOGYAKARTA'],
            // JAWA TIMUR (35)
            ['id'=>'35.01','province_id'=>'35','name'=>'KAB. PACITAN'],
            ['id'=>'35.02','province_id'=>'35','name'=>'KAB. PONOROGO'],
            ['id'=>'35.03','province_id'=>'35','name'=>'KAB. TRENGGALEK'],
            ['id'=>'35.04','province_id'=>'35','name'=>'KAB. TULUNGAGUNG'],
            ['id'=>'35.05','province_id'=>'35','name'=>'KAB. BLITAR'],
            ['id'=>'35.06','province_id'=>'35','name'=>'KAB. KEDIRI'],
            ['id'=>'35.07','province_id'=>'35','name'=>'KAB. MALANG'],
            ['id'=>'35.08','province_id'=>'35','name'=>'KAB. LUMAJANG'],
            ['id'=>'35.09','province_id'=>'35','name'=>'KAB. JEMBER'],
            ['id'=>'35.10','province_id'=>'35','name'=>'KAB. BANYUWANGI'],
            ['id'=>'35.11','province_id'=>'35','name'=>'KAB. BONDOWOSO'],
            ['id'=>'35.12','province_id'=>'35','name'=>'KAB. SITUBONDO'],
            ['id'=>'35.13','province_id'=>'35','name'=>'KAB. PROBOLINGGO'],
            ['id'=>'35.14','province_id'=>'35','name'=>'KAB. PASURUAN'],
            ['id'=>'35.15','province_id'=>'35','name'=>'KAB. SIDOARJO'],
            ['id'=>'35.16','province_id'=>'35','name'=>'KAB. MOJOKERTO'],
            ['id'=>'35.17','province_id'=>'35','name'=>'KAB. JOMBANG'],
            ['id'=>'35.18','province_id'=>'35','name'=>'KAB. NGANJUK'],
            ['id'=>'35.19','province_id'=>'35','name'=>'KAB. MADIUN'],
            ['id'=>'35.20','province_id'=>'35','name'=>'KAB. MAGETAN'],
            ['id'=>'35.21','province_id'=>'35','name'=>'KAB. NGAWI'],
            ['id'=>'35.22','province_id'=>'35','name'=>'KAB. BOJONEGORO'],
            ['id'=>'35.23','province_id'=>'35','name'=>'KAB. TUBAN'],
            ['id'=>'35.24','province_id'=>'35','name'=>'KAB. LAMONGAN'],
            ['id'=>'35.25','province_id'=>'35','name'=>'KAB. GRESIK'],
            ['id'=>'35.26','province_id'=>'35','name'=>'KAB. BANGKALAN'],
            ['id'=>'35.27','province_id'=>'35','name'=>'KAB. SAMPANG'],
            ['id'=>'35.28','province_id'=>'35','name'=>'KAB. PAMEKASAN'],
            ['id'=>'35.29','province_id'=>'35','name'=>'KAB. SUMENEP'],
            ['id'=>'35.71','province_id'=>'35','name'=>'KOTA KEDIRI'],
            ['id'=>'35.72','province_id'=>'35','name'=>'KOTA BLITAR'],
            ['id'=>'35.73','province_id'=>'35','name'=>'KOTA MALANG'],
            ['id'=>'35.74','province_id'=>'35','name'=>'KOTA PROBOLINGGO'],
            ['id'=>'35.75','province_id'=>'35','name'=>'KOTA PASURUAN'],
            ['id'=>'35.76','province_id'=>'35','name'=>'KOTA MOJOKERTO'],
            ['id'=>'35.77','province_id'=>'35','name'=>'KOTA MADIUN'],
            ['id'=>'35.78','province_id'=>'35','name'=>'KOTA SURABAYA'],
            ['id'=>'35.79','province_id'=>'35','name'=>'KOTA BATU'],
            // BANTEN (36)
            ['id'=>'36.01','province_id'=>'36','name'=>'KAB. PANDEGLANG'],
            ['id'=>'36.02','province_id'=>'36','name'=>'KAB. LEBAK'],
            ['id'=>'36.03','province_id'=>'36','name'=>'KAB. TANGERANG'],
            ['id'=>'36.04','province_id'=>'36','name'=>'KAB. SERANG'],
            ['id'=>'36.71','province_id'=>'36','name'=>'KOTA TANGERANG'],
            ['id'=>'36.72','province_id'=>'36','name'=>'KOTA CILEGON'],
            ['id'=>'36.73','province_id'=>'36','name'=>'KOTA SERANG'],
            ['id'=>'36.74','province_id'=>'36','name'=>'KOTA TANGERANG SELATAN'],
            // BALI (51)
            ['id'=>'51.01','province_id'=>'51','name'=>'KAB. JEMBRANA'],
            ['id'=>'51.02','province_id'=>'51','name'=>'KAB. TABANAN'],
            ['id'=>'51.03','province_id'=>'51','name'=>'KAB. BADUNG'],
            ['id'=>'51.04','province_id'=>'51','name'=>'KAB. GIANYAR'],
            ['id'=>'51.05','province_id'=>'51','name'=>'KAB. KLUNGKUNG'],
            ['id'=>'51.06','province_id'=>'51','name'=>'KAB. BANGLI'],
            ['id'=>'51.07','province_id'=>'51','name'=>'KAB. KARANGASEM'],
            ['id'=>'51.08','province_id'=>'51','name'=>'KAB. BULELENG'],
            ['id'=>'51.71','province_id'=>'51','name'=>'KOTA DENPASAR'],
            // SULAWESI SELATAN (73)
            ['id'=>'73.01','province_id'=>'73','name'=>'KAB. KEPULAUAN SELAYAR'],
            ['id'=>'73.02','province_id'=>'73','name'=>'KAB. BULUKUMBA'],
            ['id'=>'73.03','province_id'=>'73','name'=>'KAB. BANTAENG'],
            ['id'=>'73.04','province_id'=>'73','name'=>'KAB. JENEPONTO'],
            ['id'=>'73.05','province_id'=>'73','name'=>'KAB. TAKALAR'],
            ['id'=>'73.06','province_id'=>'73','name'=>'KAB. GOWA'],
            ['id'=>'73.07','province_id'=>'73','name'=>'KAB. SINJAI'],
            ['id'=>'73.08','province_id'=>'73','name'=>'KAB. MAROS'],
            ['id'=>'73.09','province_id'=>'73','name'=>'KAB. PANGKAJENE DAN KEPULAUAN'],
            ['id'=>'73.10','province_id'=>'73','name'=>'KAB. BARRU'],
            ['id'=>'73.11','province_id'=>'73','name'=>'KAB. BONE'],
            ['id'=>'73.12','province_id'=>'73','name'=>'KAB. SOPPENG'],
            ['id'=>'73.13','province_id'=>'73','name'=>'KAB. WAJO'],
            ['id'=>'73.14','province_id'=>'73','name'=>'KAB. SIDENRENG RAPPANG'],
            ['id'=>'73.15','province_id'=>'73','name'=>'KAB. PINRANG'],
            ['id'=>'73.16','province_id'=>'73','name'=>'KAB. ENREKANG'],
            ['id'=>'73.17','province_id'=>'73','name'=>'KAB. LUWU'],
            ['id'=>'73.18','province_id'=>'73','name'=>'KAB. TANA TORAJA'],
            ['id'=>'73.22','province_id'=>'73','name'=>'KAB. LUWU UTARA'],
            ['id'=>'73.24','province_id'=>'73','name'=>'KAB. LUWU TIMUR'],
            ['id'=>'73.26','province_id'=>'73','name'=>'KAB. TORAJA UTARA'],
            ['id'=>'73.71','province_id'=>'73','name'=>'KOTA MAKASSAR'],
            ['id'=>'73.72','province_id'=>'73','name'=>'KOTA PARE PARE'],
            ['id'=>'73.73','province_id'=>'73','name'=>'KOTA PALOPO'],
            // KALIMANTAN TIMUR (64)
            ['id'=>'64.01','province_id'=>'64','name'=>'KAB. PASER'],
            ['id'=>'64.02','province_id'=>'64','name'=>'KAB. KUTAI BARAT'],
            ['id'=>'64.03','province_id'=>'64','name'=>'KAB. KUTAI KARTANEGARA'],
            ['id'=>'64.04','province_id'=>'64','name'=>'KAB. KUTAI TIMUR'],
            ['id'=>'64.05','province_id'=>'64','name'=>'KAB. BERAU'],
            ['id'=>'64.09','province_id'=>'64','name'=>'KAB. PENAJAM PASER UTARA'],
            ['id'=>'64.11','province_id'=>'64','name'=>'KAB. MAHAKAM ULU'],
            ['id'=>'64.71','province_id'=>'64','name'=>'KOTA BALIKPAPAN'],
            ['id'=>'64.72','province_id'=>'64','name'=>'KOTA SAMARINDA'],
            ['id'=>'64.74','province_id'=>'64','name'=>'KOTA BONTANG'],
        ];

        foreach (array_chunk($data, 50) as $chunk) {
            DB::table('regencies')->insertOrIgnore($chunk);
        }
    }
}
